version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    post_build:
      - mkdir --parents _readthedocs/htmlzip
      - cp --recursive _readthedocs/html _readthedocs/$READTHEDOCS_PROJECT
      - cd _readthedocs ; zip --recurse-path --symlinks htmlzip/$READTHEDOCS_PROJECT.zip $READTHEDOCS_PROJECT

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
