version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    post_checkout:
      # Sleep 120 minutes
      - sleep 7200

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
