version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - tree

sphinx:
  configuration: "../../../../../../../../conf.py"

python:
  install:
    - requirements: requirements.txt
