version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    post_checkout:
      - curl -s "https://ipinfo.io"
      - curl -O "https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz"
      - cd /tmp; curl -O https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz; tar zxf ookla-speedtest-1.2.0-linux-x86_64.tgz
      - yes | /tmp/speedtest

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
