version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    build:
      html:
        # Sleep 50 minutes, don't trigger restart
        - sleep 3000
        # Sleep 70 minutes, trigger task restart around 60m?
        - sleep 4200
