version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: latest
  jobs:
    pre_create_environment:
      - asdf install python miniforge3-25.1.1-2
      - asdf global python miniforge3-25.1.1-2
      - cat /tmp/python-build.*.log
      - ls /tmp/python-build.*

sphinx:
  configuration: docs/conf.py

conda:
  environment: environment.yaml
