version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  jobs:
    post_checkout:
      # Skip if only non-documentation files changed (e.g., only images or data files)
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ]; then
          # Get list of changed files
          CHANGED_FILES=$(git diff --name-only origin/main)
          # Check if any changed files are documentation-related.
          # If ALL files are non-documentation (grep finds no documentation files),
          # then we skip the build by exiting with 183.
          if ! echo "$CHANGED_FILES" | grep -qE "\.(rst|md|py|yaml|yml|txt|toml)$"; then
            exit 183;
          fi
        fi

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
