version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "latest"
  commands:
    - mkdir -p _readthedocs/html/
    - echo "Build media size test" > _readthedocs/html/index.html
    - head -c 1100M /dev/zero > _readthedocs/html/big.bin
