version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "22"
  jobs:
    install:
      # "docs/" directory was created clonnig the example repository
      # https://github.com/jupyter-book/mystmd-quickstart.git
      #
      # Install mystmd dependencies
      - npm install -g mystmd@1.5.1
    post_install:
      - myst -v
      - cat /etc/hosts
    build:
      html:
        # Build the site
        - cd docs/ && myst start
    post_build:
      # Copy generated files into Read the Docs directory
      - mkdir --parents $READTHEDOCS_OUTPUT/html/
      - cp --recursive docs/_build/html/* $READTHEDOCS_OUTPUT/html/
