version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    post_install:
      - pip install snakeviz
    build:
      html:
        - mkdir -p $READTHEDOCS_OUTPUT/html
        - python -m cProfile -o profram.prof -m sphinx -T -W --keep-going -b html -d _build/doctrees -D language=en docs/ $READTHEDOCS_OUTPUT/html
        - wget https://gist.githubusercontent.com/MSSandroid/6402e2e99e31633386a312b283839e0d/raw/4890a4ac54c3dae72a634da92f84c2adc7480056/snakeviz_static_html.py
        - python snakeviz_static_html.py profram.prof 
        - mv profram.html $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
