version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "22"
  jobs:
    install:
      # "docs/" directory was created clonnig the example repository
      # https://github.com/jupyter-book/mystmd-quickstart.git
      #
      # Install mystmd dependencies
      - npm install -g mystmd
      # Force installing the latest version of remix
      # https://github.com/readthedocs/addons/issues/278#issuecomment-2278050905
      - npm install remix@rc
    post_install:
      - myst -v
    build:
      html:
        # Build the site
        - cd docs/ && myst build --html
    post_build:
      # Copy generated files into Read the Docs directory
      - mkdir --parents $READTHEDOCS_OUTPUT/html/
      - cp --recursive docs/_build/html/* $READTHEDOCS_OUTPUT/html/
