version: 2

build:
  os: ubuntu-lts-latest
  environment:
    STRING_VARIABLE: production
    BOOL_VARIABLE: true
    NUMBER_VARIABLE: 42
  jobs:
    post_checkout:
      - echo "Post-checkout step"
      - env
    pre_build:
      - echo "Pre-build step"
      - env
    build:
      html:
        - echo "Build HTML step"
        - env
  tools:
    python: latest

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
