version: 2

build:
  os: ubuntu-24.04
  tools:
    python: latest
  jobs:
    install:
      - pip install -r docs/requirements.txt
    build:
      html:
        - zensical build
    post_build:
      - cp --recursive site/* $READTHEDOCS_OUTPUT/html/