version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - pip install -r requirements.txt
    - python -m sphinx -T -E -j auto -b html -D language=en docs/ $READTHEDOCS_OUTPUT/html
