version: 2

build:
  os: "ubuntu-24.04"
  commands:
    - unset CONDA_ENVS_PATH ; unset CONDA_DEFAULT_ENV ; asdf install python miniforge3-25.1.1-2
    - asdf global python miniforge3-25.1.1-2

sphinx:
  configuration: docs/conf.py

conda:
  environment: environment.yaml
