version: 2

formats:
  - pdf

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - tree

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
