[project]
name = "test-builds"
description = "Read the Docs scenarios to test builds"
version = "0.1.0"
authors = [
    { name = "Manuel Kaufmann", email = "manuel@readthedocs.org" }
]
dependencies = [
    "sphinx>=9",
    "sphinx-autorun",
    "sphinx-rtd-theme>=3.0.0rc2"
]

[project.optional-dependencies]
dev = [
    "tox",
    "pre-commit",
    "bump2version"
]